name: noise_mapper
description: Urban Noise Mapping App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  record: ^6.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: ^5.4.3+1
  uuid: ^4.3.3
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true